version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_USER: user
    ports:
    - 3306:3306