// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"service/api/rest/internal/logic"
	"service/api/rest/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

type Handler struct {
	cul *logic.CreateUserLogic
	gul *logic.GetUserLogic
}

func NewHandler(cul *logic.CreateUserLogic, gul *logic.GetUserLogic) *Handler {
	return &Handler{
		cul: cul,
		gul: gul,
	}
}

func (h *Handler) RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/users/id",
				Handler: h.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/create",
				Handler: h.CreateUserHandler(serverCtx),
			},
		},
	)
}
