// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"infra"
	"service/api/rest/internal/handler"
	logic2 "service/api/rest/internal/logic"
	"service/internal/user/logic"
	"service/internal/user/repo"
)

// Injectors from wire.go:

func initApp() *App {
	db := infra.ProvideMySQL()
	repository := repo.NewMySQLUserRepo(db)
	logicLogic := logic.NewLogic(repository)
	createUserLogic := logic2.NewCreateUserLogic(logicLogic)
	getUserLogic := logic2.NewGetUserLogic(logicLogic)
	handlerHandler := handler.NewHandler(createUserLogic, getUserLogic)
	app := &App{
		h: handlerHandler,
	}
	return app
}
